drop table if exists imdb_dev.dim_title_genre;
create table imdb_dev.dim_title_genre
(
    title_id UUID NOT NULL,
    genre_id UUID NOT NULL,
    PRIMARY KEY (title_id, genre_id),
    CONSTRAINT fk_title_id
      FOREIGN KEY(title_id)
	  REFERENCES imdb_dev.dim_title(id),
    CONSTRAINT fk_genre_id
      FOREIGN KEY(genre_id)
	  REFERENCES imdb_dev.dim_genre(id)
) PARTITION BY LIST(genre_id);

-- Values from partitions are generated by dim_genre PK
create table dim_title_genre_default PARTITION OF imdb_dev.dim_title_genre DEFAULT;
CREATE TABLE dim_title_genre_war PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('a3f0171d-e281-aacc-c9ad-bef7d0d87ccb');
CREATE TABLE dim_title_genre_adult PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('4f09daa9-d95b-cb16-6a30-2407a0e0babe');
CREATE TABLE dim_title_genre_fantasy PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('aed34b9f-60ee-115d-fa79-18b742336277');
CREATE TABLE dim_title_genre_news PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('421b47ff-d946-ca08-3b65-cd668c6b17e6');
CREATE TABLE dim_title_genre_talkshow PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('793add6d-8887-08a0-a13a-6ca4154126c3');
CREATE TABLE dim_title_genree_gameshow PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('43861345-b16b-6a56-23bb-ad02dbe4060b');
CREATE TABLE dim_title_genre_filmnoir PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('4c028455-1e3e-67c2-1d9f-a89fc4b648ff');
CREATE TABLE dim_title_genre_adventure PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('dc1d2a4d-5918-57f0-a0dd-38b4ebcf5a72');
CREATE TABLE dim_title_genre_documentary PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('0c276336-21a2-706c-5bf3-1d3d67ee74ec');
CREATE TABLE dim_title_genre_musical PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('79ab70be-e156-2fc7-0efc-8ee0a7df99de');
CREATE TABLE dim_title_genre_romance PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('081fc8e8-bd39-e1dc-72ca-3f5a5fdf6697');
CREATE TABLE dim_title_genre_family PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('cefc4f7c-bc8c-3476-2e0f-76703e7e174e');
CREATE TABLE dim_title_genre_action PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('004bf6c9-a400-0314-0292-e97330236c53');
CREATE TABLE dim_title_genre_biography PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('9100c731-7c2f-5573-0e16-3e7e710c0a52');
CREATE TABLE dim_title_genre_thriller PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('41ce88c9-1e34-1fce-1c4d-961ef9244c32');
CREATE TABLE dim_title_genre_animation PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('d6b6b668-dbca-9d4f-e774-bb654226ebe3');
CREATE TABLE dim_title_genre_history PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('16d2b386-b203-4b94-8899-6466aaae0b57');
CREATE TABLE dim_title_genre_music PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('47dcbd83-4e66-9233-d7eb-8a51456ed217');
CREATE TABLE dim_title_genre_drama PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('205b8c9a-6b18-d476-abc9-4908e0280ea5');
CREATE TABLE dim_title_genre_mistery PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('37afd7e3-3711-38cd-5e0e-172427cb5232');
CREATE TABLE dim_title_genre_realtytv PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('b7a4d732-e64e-a95c-d9b3-ae0cb829980c');
CREATE TABLE dim_title_genre_sport PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('96faa3e6-c45b-b5a0-7bcc-0bcd3be37654');
CREATE TABLE dim_title_genre_comedy PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('e6b99f24-d056-d03f-20b4-651f79fc640e');
CREATE TABLE dim_title_genre_western PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('97a09e85-a7e1-b103-409e-fc93efa4fed1');
CREATE TABLE dim_title_genre_scifi PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('6c61d272-4763-c5bc-08ec-935933146576');
CREATE TABLE dim_title_genre_short PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('30bb747c-98bc-cdd1-1b3f-89e644c4d0ad');
CREATE TABLE dim_title_genre_crime PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('c967a0db-b291-51be-23e4-d79805a1da02');
CREATE TABLE dim_title_genre_horror PARTITION OF imdb_dev.dim_title_genre FOR VALUES IN ('6dd1b5dd-cf2d-141f-a924-bb9207874c6d');

alter table imdb_dev.dim_title_genre
    owner to dbt;

grant select on imdb_dev.dim_title_genre to api;
